Feature/card_registration_new
partithura-estagiarios/intranet-fdms-front pull request #12
Opened 2024-02-15 12:57 UTC by oGalhardo

2024-02-15 14:32 UTC, guigrasel commented on src/components/CardRegistration/InputRegistration.vue
> +  if (item.includes("ss")) {
return item.includes("ss")

2024-02-15 14:32 UTC, guigrasel commented on src/components/CardRegistration/InputRegistration.vue
> +          :name="isPwdvisible ? 'visibility_off' : 'visibility'"
cria uma computed para isso, operadores ternários não devem ser utilizados na template

2024-02-15 14:32 UTC, guigrasel commented on src/components/CardRegistration/CardRegistration.vue
> +          <q-btn size="xl" flat label="Cadastrar" />
tradução

2024-02-15 16:15 UTC, oGalhardo commented on src/components/CardRegistration/InputRegistration.vue
> +  if (item.includes("ss")) {
Feito

2024-02-15 16:15 UTC, oGalhardo commented on src/components/CardRegistration/CardRegistration.vue
> +          <q-btn size="xl" flat label="Cadastrar" />
Feito

2024-02-15 16:54 UTC, guigrasel requested changes

2024-02-15 16:54 UTC, guigrasel commented on src/components/CardRegistration/InputRegistration.vue
> +onMounted(() => {
remover

2024-02-19 12:38 UTC, oGalhardo commented on src/components/CardRegistration/InputRegistration.vue
> +onMounted(() => {
Resolvido

2024-02-19 16:35 UTC, guigrasel approved these changes

2024-02-19 16:35 UTC, merged