Feature/home
partithura-estagiarios/intranet-fdms-front pull request #14
Opened 2024-02-15 17:59 UTC by oGalhardo

2024-02-16 14:22 UTC, guigrasel requested changes

2024-02-16 14:22 UTC, guigrasel commented on src/components/Pages/Home/PHome.vue
> +  <Image_Rh img="Welcome_Intranet.png" />
pq o nome desse componente ta assim?

2024-02-16 14:22 UTC, guigrasel commented on src/components/Pages/Home/PHome.vue
> +  <Image_Rh img="Welcome_Intranet.png" />
Manter o seguinte padrão que é válido pra todos os projetos:
- Nome de componente: NomeComponente;
- Nome de branch e de pastas: nome-branch;

2024-02-16 14:22 UTC, guigrasel commented on src/components/Separator/Separator.vue
> +    <div class="text bg-green relative-position" :style="{ width: large }">
não é uma boa prática usar style inline

2024-02-16 14:22 UTC, guigrasel commented on src/components/Pages/Home/PHome.vue
> +  z-index: 1000px;
z-index não é assim que funciona

2024-02-16 14:22 UTC, guigrasel commented on src/components/Pages/Home/PHome.vue
> +  z-index: 1000px;
ele serve para separar camadas, então não faz sentido nesse caso

2024-02-19 12:29 UTC, oGalhardo commented on src/components/Pages/Home/PHome.vue
> +  z-index: 1000px;
Resolvido

2024-02-19 14:20 UTC, guigrasel approved these changes

2024-02-19 14:20 UTC, guigrasel commented on src/components/Pages/Home/PHome.vue
> +  <Separator texto="SISTEMAS" large="px-20" class="overlap" />
lembrar de traduzir

2024-02-19 14:20 UTC, merged