Feature/page_for_ramais_new
partithura-estagiarios/intranet-fdms-front pull request #18
Opened 2024-02-19 12:12 UTC by oGalhardo

![image](https://github.com/partithura-estagiarios/intranet-fdms/assets/107896110/96e70d93-7f6a-44b3-81b2-4c767eabf798)

2024-02-19 14:23 UTC, guigrasel requested changes

2024-02-19 14:23 UTC, guigrasel commented on src/components/TableRamais/AddRamal/DialogAddRamal.vue
> +            v-model.lazy="label.nameOfRamal"
o que é v-model.lazy?

2024-02-19 14:23 UTC, guigrasel commented on src/components/TableRamais/AddRamal/DialogAddRamal.vue
> +            :label="$t(`form.${labels[0]}`)"
não entendi o pq disso, só colocar a string

2024-02-19 14:23 UTC, guigrasel commented on src/components/TableRamais/HeaderRamais.vue
> +        label="Adicionar Ramal"
traduzir

2024-02-19 14:23 UTC, guigrasel commented on src/components/TableRamais/lib.ts
> +export const columns = [
traduzir

2024-02-19 14:31 UTC, oGalhardo commented on src/components/TableRamais/AddRamal/DialogAddRamal.vue
> +            v-model.lazy="label.nameOfRamal"
arrumado

2024-02-19 14:34 UTC, oGalhardo commented on src/components/TableRamais/AddRamal/DialogAddRamal.vue
> +            :label="$t(`form.${labels[0]}`)"
Resolvido

2024-02-19 14:37 UTC, oGalhardo commented on src/components/TableRamais/HeaderRamais.vue
> +        label="Adicionar Ramal"
resolvido

2024-02-19 16:24 UTC, oGalhardo commented on src/components/TableRamais/lib.ts
> +export const columns = [
traduzido

2024-02-20 11:54 UTC, guigrasel approved these changes

2024-02-20 11:54 UTC, merged