Feature/dont-return-a-page-login-if-is-logged
partithura-estagiarios/intranet-fdms-front pull request #38
Opened 2024-03-06 17:09 UTC by oGalhardo

2024-03-06 17:32 UTC, guigrasel requested changes

2024-03-06 17:32 UTC, guigrasel commented on src/components/TabHeader/ButtonDropdownSettings/BtDropSet.vue
> +const on_off = ref(false);
pq essa variavel ta em snake_case?

2024-03-06 17:32 UTC, guigrasel commented on src/modules/router.ts
> +  } else if (userStorage.stateUser.token && to.path === "/login") {
remover else if

2024-03-06 17:42 UTC, oGalhardo commented on src/components/TabHeader/ButtonDropdownSettings/BtDropSet.vue
> +const on_off = ref(false);
Resolvido

2024-03-06 17:45 UTC, oGalhardo commented on src/modules/router.ts
> +  } else if (userStorage.stateUser.token && to.path === "/login") {
Resolvido

2024-03-07 16:15 UTC, guigrasel commented on src/modules/router.ts
> +  if (!userStorage.stateUser.token && to.path !== "/login") {
não faltou um return?

2024-03-07 16:51 UTC, oGalhardo commented on src/modules/router.ts
> +  if (!userStorage.stateUser.token && to.path !== "/login") {
Resolvido

2024-03-07 20:09 UTC, guigrasel approved these changes

2024-03-07 20:09 UTC, merged