Feature/schedule-room
partithura-estagiarios/intranet-fdms-front pull request #44
Opened 2024-03-12 14:45 UTC by oGalhardo

![image](https://github.com/partithura-estagiarios/intranet-fdms-front/assets/107896110/53159c0b-168c-4f4c-82e3-dc0119d10ebf)

2024-03-13 11:35 UTC, guigrasel requested changes

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +  console.log(`T${receivedTimeInitial.value}:00+00:00`);
remover logs

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/addScheduleRoom/addScheduleRoom.vue
> +  console.log(
remover

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +        <input-date-time @envity-date="handleDateSelection" />
pq o nome do componente ta input-date-time?

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +        <input-date-time @envity-date="handleDateSelection" />
deve seguir o padrão dos demais: InputDateTime

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +    receivedData.value + `T${receivedTimeFinal.value}:00+00:00`;
isso aq n precisa ser feito

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +watchEffect(() => {
pq ta atribuindo esse tanto de coisa dentro desse watchEffect?

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +const receivedTimeFinal = ref("");
cria um objeto 'form' para evitar esse tanto de variáveis.

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +const receivedTimeFinal = ref("");
provavelmente vai ser um reactive

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/InputTime.vue
> +    return negativeNotify("Horário inválido");
acho que uma maneira melhor de mostrar esse erro pro usuário é passar uma mensagem de erro pro input

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/InputTime.vue
> +    return negativeNotify("Horário inválido");
na prop errors ou error

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/addScheduleRoom/addScheduleRoom.vue
> +<style scoped>
não ta usando

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/addScheduleRoom/lib.ts
> +export const inputsForScheduleRoom = [
isso aqui ser um array só ta te atrapalhando

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/addScheduleRoom/lib.ts
> +export const inputsForScheduleRoom = [
usa um objeto, vai facilitar

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/addScheduleRoom/addScheduleRoom.vue
> +const inputs = ref(inputsForScheduleRoom[0]);
isso n deve ser um array, e tu n precisa passar isso por prop aqui

2024-03-13 11:35 UTC, guigrasel commented on src/components/ScheduleRoom/addScheduleRoom/addScheduleRoom.vue
> +const inputs = ref(inputsForScheduleRoom[0]);
pode importar essa constante dentro do próprio InputsSection

2024-03-20 16:54 UTC, whoistaiza commented on src/components/ScheduleRoom/SectionOfInput/InputDateTime/CardDateTime.vue
> +  <q-dialog v-model="props.showCard" class="">
da pra remover esse class sem nada

2024-03-20 16:58 UTC, whoistaiza commented on src/components/ScheduleRoom/SectionOfInput/InputNormal.vue
> +function verifyInput(item) {
acho que essa função não tem necessidade, só usar o verifyTypeOfInput direto na template

2024-03-20 17:00 UTC, whoistaiza commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +      @envity-dates="(dates) => (formScheduleRoom.options.value = dates)"
por que não usa o v-model dos inputs?

2024-03-20 17:00 UTC, whoistaiza commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +      Materiais de Apoio
Sem tradução

2024-03-20 17:01 UTC, whoistaiza commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +        label="Outras Ex: Canetas, Folhas A4"
não tem tradução?

2024-03-20 17:01 UTC, whoistaiza commented on src/components/ScheduleRoom/SectionOfInput/SelectRoom.vue
> +      label="Selecione uma sala"
tradução

2024-03-20 17:02 UTC, whoistaiza commented on src/components/ScheduleRoom/addScheduleRoom/AddScheduleRoom.vue
> +        <q-btn color="green" label="Confirmar" @click="saveRoom()" />
traducao

2024-03-20 17:07 UTC, whoistaiza approved these changes

2024-03-20 19:37 UTC, guigrasel requested changes
tem uns comentario ai

2024-03-20 19:37 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/InputDateTime/InputDateTime.vue
> +    label="Data e Hora de Início"
tradução

2024-03-20 19:37 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/InputDateTime/InputDateTime.vue
> +    label="Data e Hora Final"
tradução

2024-03-21 10:55 UTC, oGalhardo commented on src/components/ScheduleRoom/SectionOfInput/InputDateTime/CardDateTime.vue
> +  <q-dialog v-model="props.showCard" class="">
Rsolvido

2024-03-21 11:03 UTC, oGalhardo commented on src/components/ScheduleRoom/SectionOfInput/InputNormal.vue
> +function verifyInput(item) {
Rsolvido

2024-03-21 11:13 UTC, oGalhardo commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +      Materiais de Apoio
Resolvido

2024-03-21 11:19 UTC, oGalhardo commented on src/components/ScheduleRoom/SectionOfInput/InputSection.vue
> +        label="Outras Ex: Canetas, Folhas A4"
Corrigi

2024-03-21 11:22 UTC, oGalhardo commented on src/components/ScheduleRoom/addScheduleRoom/AddScheduleRoom.vue
> +        <q-btn color="green" label="Confirmar" @click="saveRoom()" />
Arrumei

2024-03-21 11:27 UTC, oGalhardo commented on src/components/ScheduleRoom/SectionOfInput/InputDateTime/InputDateTime.vue
> +    label="Data e Hora de Início"
Corrigi

2024-03-21 11:27 UTC, oGalhardo commented on src/components/ScheduleRoom/SectionOfInput/InputDateTime/InputDateTime.vue
> +    label="Data e Hora Final"
Corrigi

2024-03-21 11:34 UTC, guigrasel approved these changes

2024-03-21 11:34 UTC, guigrasel commented on src/components/ScheduleRoom/SectionOfInput/SelectRoom.vue
> +      label="Selecione uma sala"
aqui faltou ainda

2024-03-21 11:34 UTC, merged