Create-table-for-schedule-room
partithura-estagiarios/intranet-fdms-front pull request #45
Opened 2024-03-15 11:13 UTC by oGalhardo

2024-03-15 11:32 UTC, guigrasel requested changes

2024-03-15 11:32 UTC, guigrasel commented on src/components/Pages/ScheduleRoom/Month.vue
> +  return "en-CA";
pq ta passando default pra inglês?

2024-03-15 11:32 UTC, guigrasel commented on src/components/Pages/ScheduleRoom/PScheduleRoom.vue
> +.display-flex {
tem a classe row do quasar pra isso.

2024-03-15 11:32 UTC, guigrasel commented on src/components/Pages/ScheduleRoom/PScheduleRoom.vue
> +.calendarM {
nome de classe seguir o padrao kebab-case

2024-03-15 11:32 UTC, guigrasel commented on src/components/Pages/ScheduleRoom/lib.ts
> +export const countryCodes = {
desnecessário isso, portugues e ingles, apenas

2024-03-15 11:32 UTC, guigrasel commented on src/components/Pages/ScheduleRoom/lib.ts
> +export const countryCodes = {
tu ta fazendo a intranet da fundimisa

2024-03-15 11:32 UTC, guigrasel commented on src/components/Pages/ScheduleRoom/lib.ts
> +];
```suggestion
export const rooms = [
  { name: "SALA_A", color: "red" },
  { name: "SALA_B", color: "green" },
  { name: "SALA_C", color: "yellow" },
  { name: "SALA_DE_REUNIÃO", color: "orange" },
];
```

2024-03-15 11:32 UTC, guigrasel commented on src/components/Pages/ScheduleRoom/lib.ts
> +];
remover os espaços dessas constantes

2024-03-15 14:56 UTC, oGalhardo commented on src/components/Pages/ScheduleRoom/Month.vue
> +  return "en-CA";
resolvido

2024-03-20 17:01 UTC, guigrasel approved these changes

2024-03-20 17:01 UTC, merged