✨ Card de processos
partithura-estagiarios/intranet-fdms-front pull request #48
Opened 2024-04-02 14:21 UTC by oGalhardo

![image](https://github.com/partithura-estagiarios/intranet-fdms-front/assets/107896110/9e16cd06-cbf8-499a-a714-e3787b49ecaf)

2024-04-02 17:13 UTC, julianostroschon requested changes

2024-04-02 17:13 UTC, julianostroschon commented on .env.example
mantenha um exemplo no `example`

2024-04-02 17:13 UTC, julianostroschon commented on src/components/CardForDocSIG/Card.vue
> +  console.log(file);
remover
```suggestion
```

2024-04-02 17:13 UTC, julianostroschon commented on src/stores/files.ts
> +          return console.log("Arquivo enviado com sucesso:", filename);
```suggestion
```

2024-04-02 17:13 UTC, julianostroschon commented on src/stores/files.ts
> +          console.log("Arquivo excluído:", data);
```suggestion
```

2024-04-02 17:14 UTC, julianostroschon commented
no exemplo que tu apresentou na descrição, está com o estilo bem fraco, dá pra melhorar

2024-04-05 14:32 UTC, oGalhardo commented on src/components/CardForDocSIG/Card.vue
> +  console.log(file);
Resolvido

2024-04-05 14:32 UTC, oGalhardo commented on src/stores/files.ts
> +          return console.log("Arquivo enviado com sucesso:", filename);
Resolvido

2024-04-05 18:11 UTC, oGalhardo commented on .env.example
Arrumadi

2024-04-30 13:08 UTC, whoistaiza commented
Achei o design confuso, não entendi o que é pra ser esses 'a' e 'b' perdido, se for labels muda pra um exemplo melhor pra contextualizar

2024-04-30 13:09 UTC, taizamoura commented on locales/br/text.ts
> +  addArchive: "Adicionar Arquivo",
redundante com o addFile no action.ts

2024-04-30 13:11 UTC, whoistaiza commented on src/components/CardForDocSIG/CardProcess/CardProcess.vue
> +                activeButtonIndex === null || activeButtonIndex === index,
Essa condições podiam ficar no script ao invés da template

2024-04-30 13:11 UTC, taizamoura commented on src/components/CardForDocSIG/CardProcess/CardProcess.vue
> +              :class="{ 'text-white': activeButtonIndex === index }"
essa também

2024-04-30 13:12 UTC, whoistaiza commented on src/components/CardForDocSIG/CardProcess/CardProcess.vue
> +                v-if="item.folderNow !== ''"
essa tb

2024-04-30 13:13 UTC, whoistaiza commented on src/components/CardForDocSIG/CardProcess/CardProcess.vue
> +}
ta usando essa classe?

2024-04-30 13:15 UTC, whoistaiza commented on src/components/CardForDocSIG/TabForCard/AddFile.vue
> +      v-if="typeFile === 'PDF' && !isSourceFolder"
v-if="showFile"

2024-04-30 13:20 UTC, whoistaiza requested changes

2024-04-30 13:20 UTC, whoistaiza commented on src/components/CardForDocSIG/TabForCard/AddFile.vue
> +      return window.location.reload();
por que ta forçando o reload? não deveria ser necessário

2024-04-30 13:20 UTC, whoistaiza commented on src/components/CardForDocSIG/TabForCard/AddFile.vue
> +  return props.folder === "Pastas de origem";
"Pastas de origem" é uma `magic string`

2024-04-30 13:20 UTC, whoistaiza commented on src/components/CardForDocSIG/TabForCard/lib.ts
> +  //   { name: "institutional" },
vão ficar comentadas mesmo?

2024-04-30 20:12 UTC, guigrasel commented on locales/br/action.ts
> +  stillFiles: "Ainda há arquivos na pasta, delete os primeiro",
```suggestion
  stillFiles: "Ainda há arquivos na pasta, delete-os primeiro",
```

2024-04-30 20:12 UTC, guigrasel commented on src/components/CardForDocSIG/Card.vue
> +.position-options {
nao ta usando nesse componmente

2024-04-30 20:14 UTC, guigrasel commented on src/components/CardForDocSIG/TabForCard/AddFile.vue
> +    console.error("Error add file:", error);
não tem pq esse erro, só mostrar o erro para o usuário na notificação

2024-04-30 20:14 UTC, guigrasel commented on src/components/CardForDocSIG/TabForCard/DeleteFile.vue
> +    console.error("Error loading files:", error);
troca pra uma notificação de erro

2024-04-30 20:14 UTC, guigrasel commented on src/components/CardForDocSIG/TabForCard/DeleteFile.vue
> +    console.error("Error delete file:", error);
não precisa esses console.error

2024-04-30 20:14 UTC, guigrasel commented on src/components/CardForDocSIG/TabForCard/DeleteFile.vue
> +  if (props.folder === "Pastas de origem") {
Pastas de origem?

2024-05-03 12:09 UTC, junior1384 commented on src/components/CardForDocSIG/Card.vue
> +.position-options {
Sem isso o card que contém o cardProcessos quebra as dimensões

2024-05-03 12:30 UTC, julianostroschon requested changes
Favor revisar

2024-05-03 12:30 UTC, julianostroschon commented on src/components/CardForDocSIG/TabForCard/ConfirmExclusion.vue
> +  window.location.reload();
pq o reload?

2024-05-03 12:30 UTC, julianostroschon commented on src/components/CardForDocSIG/TabForCard/DeleteFile.vue
> +    return window.location.reload();
ainda reload

2024-05-03 12:30 UTC, julianostroschon commented on src/stores/files.ts
> +  "VITE_URL_BACK_SERVER_EXPRESS_FOR_ARCHIVES",
que nome é esse?

2024-05-03 12:30 UTC, julianostroschon commented on src/stores/files.ts
> +          return window.open(pdfUrl, "_blank");
window?

2024-05-14 17:00 UTC, whoistaiza commented on locales/br/action.ts
> +  addFile: "Adicionar um Arquivo",
porque arquivo em letra maiúscula?

2024-05-14 17:00 UTC, taizamoura commented on locales/br/action.ts
> +  deleteFile: "Deletar um Arquivo",
porque arquivo em letra maiúscula?

2024-05-14 17:01 UTC, whoistaiza commented on locales/br/cardDocSig.ts
> +  evaluateConformitiesImprovements: "Avaliar Conformidadese e Melhorias",
Conformidadese? Não seria Conformidade? 

Acho que só a primeira letra da frase em maiúsculo e nomes próprios.

2024-05-14 17:01 UTC, whoistaiza commented on locales/br/text.ts
> +  searchArchive: "Procurar Arquivo",
Por que arquivo em maiúsculo?

2024-05-14 17:01 UTC, whoistaiza commented on locales/en/action.ts
> +  addFile: "Add a File",
por que em maiúsculo?

2024-05-14 17:03 UTC, whoistaiza commented on src/components/CardForDocSIG/Card.vue
>  .box-shadow {
pelo que vi essa classe não ta mais em uso

2024-05-14 17:03 UTC, whoistaiza commented on src/components/CardForDocSIG/Card.vue
> +.position-options {
ta sendo usada?

2024-05-14 17:04 UTC, whoistaiza commented on src/components/CardForDocSIG/Card.vue
> +.max-height-card-sectio {
sectio mesmo?

2024-05-14 17:10 UTC, whoistaiza commented on src/components/CardForDocSIG/CardProcess/RootFolders.vue
> +const textClass = computed(() => {
acho que isso deveria ser um método

2024-05-14 17:11 UTC, whoistaiza commented on src/components/CardForDocSIG/CardProcess/lib.ts
> +}
export function showFolder(folder: Folder): Boolean {
  return !!folder.folderNow
}

2024-05-14 17:11 UTC, whoistaiza commented on src/components/CardForDocSIG/TabForCard/AddFile.vue
> +    <div v-if="isChild === 'folderChild'">
folderChild é uma magic string

2024-05-14 17:16 UTC, whoistaiza commented on src/components/CardForDocSIG/TabForCard/ConfirmExclusion.vue
> +}
async function setTitle(folderName: string) {
  const { loadFiles }: { loadFiles: Files } = await runQuery(LoadFiles, {
    folder: folderName,
  });
  title.value = isEmpty(loadFiles) ? t("action.deleteSureFile") : t("action.stillFiles")
}

2024-05-14 17:17 UTC, whoistaiza commented on src/components/CardForDocSIG/TabForCard/DeleteFile.vue
> +});
```
const enableSelect = computed(() => {
  return !isEmpty(options) && first(options).name === "";
});
```

2024-05-14 17:18 UTC, whoistaiza commented on src/components/CardForDocSIG/TabForCard/SelectFolder.vue
> +    v-if="props.version == 'add'"
magic string

2024-05-14 17:18 UTC, taizamoura commented on src/components/CardForDocSIG/TabForCard/SelectFolder.vue
> +    v-if="props.version == 'delete'"
magic string

2024-05-14 17:20 UTC, whoistaiza commented on src/components/CardForDocSIG/TabForCard/lib.ts
> +}
```
  if (files.folders && !isEmpty(files.folders)) {
    const folderNow = first(files.folders)?.folderNow;
    if (!files.archives || folderNow === "") {
      return true;
    }
  }
  return false;
}
```

2024-05-14 17:21 UTC, whoistaiza commented on src/components/CardForDocSIG/TabForCard/lib.ts
> +}
```
export function isEmpty(files: Files) {
   if (files.folders && !isEmpty(files.folders)) {
    const folderNow = first(files.folders)?.folderNow;
    if (!files.archives || folderNow === "") {
      return true;
    }
  }
  return false;
}
} 
```

2024-05-14 17:26 UTC, whoistaiza approved these changes

2024-05-20 14:25 UTC, whoistaiza approved these changes

2024-05-21 17:07 UTC, guigrasel commented on locales/br/action.ts
> +  stillFiles: "Ainda há arquivos na pasta, deseja deletar a pasta mesmo assim?",
```suggestion
  stillFiles: "Ainda há arquivos na pasta, deletar mesmo assim?",
```

2024-05-29 13:19 UTC, julianostroschon commented on locales/br/text.ts
> +  folder: "Pasta",
pluralização

2024-05-29 13:30 UTC, julianostroschon commented on src/components/CardForDocSIG/CardProcess/RootFolders.vue
> +});
```suggestion
watchEffect(async () => {
  if (!fileStorage.getReloadState || !fileStorage.getFolderTree) {
    return 
  }
  if (fileStorage.getReloadState) {
    fileStorage.toggleReloadState();
  }

  if (fileStorage.getFolderTree && !fileStorage.getFolder) {
    activeButtonIndex.value = null;
  }
  folderTreeList.value = await fileStorage.loadFolders(
    fileStorage.getFolderTree,
  );
  if (!folderTreeList.value.includes(fileStorage.getFolder)) {
    return (activeButtonIndex.value = null);
  }
});
```

2024-05-29 13:34 UTC, julianostroschon commented on src/components/CardForDocSIG/CardProcess/ShowArchives.vue
> +    console.log("arquivos");
remover

2024-05-29 13:57 UTC, merged