Bug/arrumando-estilo-tela-de-início
partithura-estagiarios/intranet-fdms-front pull request #66
Opened 2024-05-21 14:28 UTC by oGalhardo

2024-05-23 13:12 UTC, guigrasel commented on locales/br/text.ts
> +  welcomeIntranet: "Bem-vindo a nossa Intranet",
```suggestion
  welcomeIntranet: "Bem-vindo à nossa intranet",
```

2024-05-23 13:13 UTC, guigrasel commented on src/components/Image/ImageRh.vue
> +  width: 70vh;
tá usando pra largura medida proporcional a altura?

2024-05-23 13:14 UTC, guigrasel commented on src/components/Image/ImageRh.vue
> +  width: 70vh;
isso deve estar quebrando conforme a altura da tela diminuir

2024-05-23 13:15 UTC, guigrasel commented on src/components/Image/ImageRh.vue
> +  font-size: 1.9vh;
não usa vh, usa rem

2024-05-23 13:15 UTC, guigrasel commented on src/components/TabHeader/ButtonDropdownSettings/BtDropSet.vue
> +  <div class="my-card3" v-show="card"></div>
melhorar nome dessas classes my-card

2024-05-23 13:18 UTC, guigrasel requested changes
remover estilizações utilizando 'vh', essa medida é proporcional à altura da viewport, então quando modificamos essa altura com a tela minimizada, ou com diferentes monitores esse tamanho vai seguir sendo proporcional ao tamanho da tela, quebrando o layout.

A minha sugestão é trocar a medida vh para rem.

2024-05-23 13:21 UTC, julianostroschon requested changes
favor revisar

2024-05-23 13:21 UTC, julianostroschon commented on .gitignore
isso funciona?

2024-05-23 17:24 UTC, guigrasel approved these changes

2024-05-23 17:24 UTC, guigrasel commented on locales/br/text.ts
> +  welcomeIntranet: "Bem-vindo a nossa Intranet",
craze no 'a'

2024-05-29 14:01 UTC, julianostroschon approved these changes

2024-06-13 13:54 UTC, guigrasel approved these changes

2024-06-13 13:55 UTC, merged