Bug/arrumando-estilo-tela-do-agendador
partithura-estagiarios/intranet-fdms-front pull request #67
Opened 2024-05-27 14:50 UTC by oGalhardo

Novo style do agedador

2024-05-27 16:41 UTC, guigrasel commented on src/components/Pages/ScheduleRoom/BadgeEvents.vue
> +      <div v-if="index < 9">
poderia criar uma computed pra isso, e esse 9 é um magic number

2024-05-27 16:41 UTC, guigrasel commented on src/components/Pages/ScheduleRoom/BadgeEvents.vue
> +      ... <q-tooltip> +{{ getEventsByDate(props.data).length - 8 }}</q-tooltip>
magic number? o que significa esse 8?

2024-05-27 16:43 UTC, whoistaiza requested changes

2024-05-27 16:43 UTC, whoistaiza commented on src/components/Pages/ScheduleRoom/PScheduleRoom.vue
> +  const daysOfWeek = [
E quanto tiver em inglês? Acho que essa chave deveria estar na biblioteca de tradução

2024-05-27 16:43 UTC, whoistaiza commented on src/components/Pages/ScheduleRoom/lib.ts
> +  const formattedDayOfWeek = dayOfWeekShort.replace("-feira", "");
tradução

2024-05-27 16:44 UTC, guigrasel commented on src/components/Pages/ScheduleRoom/PScheduleRoom.vue
> +  ];
tradução

2024-05-27 16:46 UTC, guigrasel reviewed
![2024-05-27_13-45](https://github.com/partithura-estagiarios/intranet-fdms-front/assets/91749996/00fee7f4-ce5c-45e6-b241-4472a4254d56)

adiciona um espaço entre a cor e o título, vai ficar melhor visualmente.

2024-05-29 12:16 UTC, whoistaiza approved these changes

2024-05-29 13:21 UTC, guigrasel approved these changes

2024-06-13 13:20 UTC, julianostroschon approved these changes

2024-06-13 13:20 UTC, merged